### ISSUE TITLE
[feature request] Add URL to repository/homepage/...?

### ISSUE THREAD

**Issue by mwerle** [BenjaminCronin/KerbalChangelog#14]
Would be nice to add a URL along with the author and license so people can easily jump to the homepage (or whatever) of the mod for more information.

Perhaps make the title clickable?

**Comment by AmberCronin** [comment]
So sorry I didn't see this until now! GitHub didn't send me an email about any of the recent issues, for some reason (not my buggy code >:[ )

I believe I looked into this in the past, and I'll see what I can do about it. This is going to be a little more challenging, but again, I'll see what I can do. :)

**Comment by AmberCronin** [comment]
Added in commit e5215d8

**Comment by AmberCronin** [comment]
Actually added in commit ec611d1
:P

**Comment by mwerle** [comment]
Awesome, thank you :)
