### ISSUE TITLE
Enhancement/Feature Request: date and forKSP fields

### ISSUE THREAD

**Issue by zer0Kerbal** [BenjaminCronin/KerbalChangelog#15]
So just two more informative fields:
```
VERSION
{
  version = x.y.z 
  versionName = Bad Banana!
  versionDate = 2020 Mar 15
  versionKSP = 1.9.1
  change = thank you in advance. 
  change = that darn zer0Kerbal!
  CHANGE
  {
    change = added two new fields
    subchange = versionDate: text field for version release date
    subchange = versionKSP: text (or version) field for version KSP version target
  }
}
```

**Comment by AmberCronin** [comment]
@zer0Kerbal So sorry I didn't see this until now!
I'd be happy to add those fields in, just as long as you know that I'm not going to be able to lock anyone out of the game (it would only display along side the other information about the mod). I think that if a mod truly requires a certain game version, that should be up to the mod to implement the lock.

**Comment by AmberCronin** [comment]
Added in commit e96cfd4a8415bd20d8922b07ac4118663e72084a
